<a href="https://colab.research.google.com/github/richardmukechiwa/PyTorchSeriesandProject/blob/main/ReadyTensorProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
!pip list


Package                            Version
---------------------------------- -------------------
absl-py                            1.4.0
accelerate                         1.1.1
aiohappyeyeballs                   2.4.4
aiohttp                            3.11.9
aiosignal                          1.3.1
alabaster                          1.0.0
albucore                           0.0.19
albumentations                     1.4.20
altair                             4.2.2
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.5.1
arviz                              0.20.0
astropy                            6.1.7
astropy-iers-data                  0.2024.12.2.0.35.34
astunparse                         1.6.3
async-timeout                      4.0.3
atpublic                           4.1.0
attrs                              24.2.0
audioread           

### **First Topic: Tensors In Deep Learning**

- A torch.Tensor is a multi dimensional matrix containing elements of a single data type
- Similar to Numpy Arrays, but works better on GPU
- default data type of float32
- more suitable for deep learning than numpy array

In [77]:
import torch
import numpy as np

**LISTS**

In [79]:
my_list = [[1,2,3,4,5,6],[7,8,9,10,11,12]]
my_list

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]

**NUMPY** **ARRAYS**

In [80]:
np1 = np.random.rand(5,4)
np1

array([[0.80736763, 0.21853536, 0.83801997, 0.3288206 ],
       [0.78978206, 0.17940638, 0.1241356 , 0.33492776],
       [0.61313935, 0.81941981, 0.45182624, 0.80266813],
       [0.74438225, 0.27469056, 0.21704488, 0.72574776],
       [0.9778672 , 0.41563062, 0.56500081, 0.52287498]])

In [81]:
np1.dtype

dtype('float64')

**TENSORS**

In [ ]:
tensor

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Using **Reshape** and **View**

In [3]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
#Reshape using (-1) if the shape of the items is unknown
my_torch1 = torch.arange(15)
my_torch1


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
#Example 1
my_torch1 = my_torch1.reshape(5, -1)
my_torch1

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [13]:
# Example 2
my_torch2 = torch.arange(20)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [14]:
my_torch2 = my_torch2.reshape(-1, 5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [15]:
# Example 3

In [16]:
my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
my_torch3 = my_torch3.view(3, -1)
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [22]:
# The difference between reshape and view in Pytorch
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch


[link text](https://)

In [23]:
# with reshape and view, they will update

In [33]:
my_torch4 = torch.arange(12)
my_torch4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
my_torch4[3] =332
my_torch4

tensor([  0,   1,   2, 332,   4,   5,   6,   7,   8,   9,  10,  11])

In [36]:
my_torch5 = my_torch4.reshape(3,4)
my_torch5

tensor([[  0,   1,   2, 332],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]])

**Slices**

In [38]:
# Example
my_torch7 = torch.arange(15)
my_torch7

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
#access a specific item
my_torch7[4]

tensor(4)

In [41]:
# access a slice
my_torch8 = my_torch7.reshape(5, 3)
my_torch8

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [43]:
my_torch8[:,2]


tensor([ 2,  5,  8, 11, 14])

In [46]:
my_torch8[:,1:]

tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14]])

**Second Topic: TENSOR MATH OPERATIONS**

- Add, Subtract, Multiply, Divide, Remainders, Exponents
- Shorthand & Longhand
- Reassignment

In [49]:
import torch
import numpy as np

In [54]:
tensor_a = torch.tensor([1, 2, 3, 4, 5, 6])
tensor_b = torch.tensor([7, 8, 9, 10, 11, 12])

In [55]:
# Addition
tensor_a + tensor_b # tensor in position 1 for tensor_a gets added to the tensor_b in position 1 for tensor_b

tensor([ 8, 10, 12, 14, 16, 18])

In [56]:
# Long hand
torch.add(tensor_a, tensor_b)

tensor([ 8, 10, 12, 14, 16, 18])

In [57]:
# Subtract
tensor_a - tensor_b


tensor([-6, -6, -6, -6, -6, -6])

In [58]:
# Sub function
torch.sub(tensor_b, tensor_a)


tensor([6, 6, 6, 6, 6, 6])

In [59]:
#Multiplication
tensor_a * tensor_b

tensor([ 7, 16, 27, 40, 55, 72])

In [61]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 7, 16, 27, 40, 55, 72])

In [62]:
# Division
tensor_a /tensor_b

tensor([0.1429, 0.2500, 0.3333, 0.4000, 0.4545, 0.5000])

In [63]:
#Division long hand
torch.div(tensor_a, tensor_b)

tensor([0.1429, 0.2500, 0.3333, 0.4000, 0.4545, 0.5000])

In [66]:
# Remainders/modulo
tensor_b % tensor_a

tensor([0, 0, 0, 2, 1, 0])

In [67]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 0, 2, 1, 0])

In [68]:
#Exponent/ power
tensor_a ** tensor_b

tensor([         1,        256,      19683,    1048576,   48828125, 2176782336])

In [69]:
# Longhand Exponent
torch.pow(tensor_a, tensor_b)

tensor([         1,        256,      19683,    1048576,   48828125, 2176782336])

In [70]:
#Anothe way for longhand
tensor_a.add(tensor_b)

tensor([ 8, 10, 12, 14, 16, 18])

In [71]:
# Reassignment
tensor_a + tensor_b

tensor([ 8, 10, 12, 14, 16, 18])

In [74]:
tensor_a.add_(tensor_b)

tensor([ 8, 10, 12, 14, 16, 18])

In [75]:
tensor_a # notice the power of _ underscore, tensor_a has changed values

tensor([ 8, 10, 12, 14, 16, 18])